---
site_name: Looking Glass

theme: readthedocs

nav:
  - Home: index.md
  - Configuration Settings: configuration.md
  - Routers Setups:
    - BIRD: bird.md
    - Cisco: cisco.md
    - Cisco IOS XR: cisco_iosxr.md
    - FRRouting: frr.md
    - Juniper: juniper.md
    - Quagga: quagga.md
    - Vyatta, VyOS, EdgeOS: vyatta.md
