---
site_name: Looking Glass

theme: readthedocs

nav:
  - Home: index.md
  - Configuration Settings: configuration.md
  - Using Docker: docker.md
  - Routers Setups:
    - BIRD: routers/bird.md
    - Cisco: routers/cisco.md
    - Cisco IOS XR: routers/cisco_iosxr.md
    - FRRouting: routers/frr.md
    - Juniper: routers/juniper.md
    - Quagga: routers/quagga.md
    - Vyatta, VyOS, EdgeOS: routers/vyatta.md
